a. Import the "numpy" library as "np".

In [13]:
import numpy as np

b. Create an array of shape (2, 3, 4) of zeros.

In [14]:
ary = np.zeros((2,3,4))
print(ary)

[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]


c. Create an array of shape (2, 3, 4) of ones

In [15]:
ary = np.ones((2,3,4))
print(ary)

[[[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]]


d. Create an array with values 0 to 999 using the "np.arange" function

In [8]:
ary = np.arange(1000)
print(ary)

e. Create an array from the list [2, 3.2, 5.5, -6.4, -2.2, 2.4] and assign it to the variable "a"

In [11]:
a = np.array([2, 3.2, 5.5, -6.4, -2.2, 2.4])
print(a)

[ 2.   3.2  5.5 -6.4 -2.2  2.4]


f. Do you know what a[1] will equal? Print it to see

In [12]:
print(a[1])

3.2


g. Try printing a[1:4] to see what that equals

In [16]:
print(a[1:4])

[ 3.2  5.5 -6.4]


h. Create a 2-D array from the following list and assign it to the variable "a":
[[2, 3.2, 5.5, -6.4, -2.2, 2.4],
[1, 22, 4, 0.1, 5.3, -9],
[3, 1, 2.1, 21, 1.1, -2]]

In [17]:
a = np.array([[2, 3.2, 5.5, -6.4, -2.2, 2.4], 
              [1, 22, 4, 0.1, 5.3, -9], 
              [3, 1, 2.1, 21, 1.1, -2]])

i. Can you guess what the following slices are equal to? Print them to check your understanding.
a[:, 3]
a[1:4, 0:4]
a[1:, 2]

In [25]:
print(a[:4,:])
print(a[1:4,0:4])
print(a[1:,2])

[[  2.    3.2   5.5  -6.4  -2.2   2.4]
 [  1.   22.    4.    0.1   5.3  -9. ]
 [  3.    1.    2.1  21.    1.1  -2. ]]
[[  1.   22.    4.    0.1]
 [  3.    1.    2.1  21. ]]
[ 4.   2.1]


j. Create a 2-D array of shape (2, 4) containing two lists (range(4), range(10, 14))
and assign it to the variable "arr".Print the shape of the array. Print the size of the array. Print the maximum and minimum of the array

In [26]:
arr= np.array([range(4), range(10,14)])

In [30]:
print(arr.shape)
print(arr.size)

(2, 4)
8


In [31]:
print(arr.max());
print(arr.min())

13
0


k. Continue to use the array "arr" as defined above.Print the array re-shaped to (2, 2, 2).Print the array transposed.Print the array flattened to a single dimension. Print the array converted to floats.

In [34]:
print(arr.reshape((2,2,2)))
print(arr.T)
print(arr.reshape(8))
print(arr.astype(float))

[[[ 0  1]
  [ 2  3]]

 [[10 11]
  [12 13]]]
[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]]
[ 0  1  2  3 10 11 12 13]
[[  0.   1.   2.   3.]
 [ 10.  11.  12.  13.]]


l. Create an an array counting from 1 to 20 inclusive

In [35]:
arr= np.array(range(1,21))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


m. The array of multiples of 3 greater than 0 and less than 30

In [36]:
arr = np.array([x for x in range(1,30) if x % 3 == 0])
print(arr)

[ 3  6  9 12 15 18 21 24 27]


n. The array of 8 equally spaced floats x where 0 ≤ x ≤ 1

In [37]:
arr = np.linspace(0.0, 1.0, num=8, endpoint=False)
print(arr)

[ 0.     0.125  0.25   0.375  0.5    0.625  0.75   0.875]


o. Use np.arange and reshape to create the array A = [[1 2 3 4] [5 6 7 8]]

In [38]:
A = np.array(np.arange(1,9))
print(A.reshape(2,4))

[[1 2 3 4]
 [5 6 7 8]]


p. Use np.array to create the array B = [1 2]

In [40]:
B = np.array([1,2])
print(B)

[1 2]


q. Use broadcasting to add B to A to create the final array A + B

In [41]:
A = np.array(np.arange(1,9))
A = A.reshape(4,2)
B = np.array([1,2])
print(A+B)

[[ 2  4]
 [ 4  6]
 [ 6  8]
 [ 8 10]]
